
// autogenerated by brownie
// do not modify the existing settings
module.exports = {
    networks: {
        hardhat: {
           forking: {
               url: "https://eth-mainnet.alchemyapi.io/v2/y-8YztRvt8o4wfcwJyvJ7pDo8WgP7kUa"
           },
           chainId: 1
       }
    }
}